FROM node:16-alpine

WORKDIR /app

COPY package.json package-lock.json .env.local ./
RUN npm install

COPY tsconfig.json postcss.config.js tailwind.config.js ./
COPY /hooks ./hooks
COPY /modules ./modules
COPY /pages ./pages
COPY /public ./public
COPY /styles ./styles
COPY /lib ./lib
COPY /models ./models

RUN npm i -g next
RUN next build

CMD ["next", "start"]