version: '3.9'

services:
  app:
    image: matay-app-production
    build:
      dockerfile: Dockerfile.production
    env_file:
      - .env.local
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo:5.0.8-focal
    ports:
      - 27018:27017
    volumes:
      - matay-db:/data/db

volumes:
  matay-db: {}
