version: '3.9'

services:
  app:
    image: matay-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./modules:/app/modules
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles

  db:
    image: mongo:5.0.8-focal
    ports:
      - 27018:27017
    volumes:
      - matay-db:/data/db

volumes:
  matay-db: {}
